import com.nzuwera.api.domain.OrderRequest;

rule "Discount for CARD payment above 10000"
    when
        orderObject : OrderRequest( paymentType=="CARD" && totalPrice > 10000 );
    then
        orderObject.setDiscount(15);
end;

rule "Discount for CARD payment between 5000 and 10000"
    when
        orderObject : OrderRequest( paymentType=="CARD" && totalPrice > 5000 && totalPrice < 10000 );
    then
        orderObject.setDiscount(5);
end;

rule "Discount for CARD payment below 5000"
    when
        orderObject : OrderRequest( paymentType=="CARD" && totalPrice < 5000 );
    then
        orderObject.setDiscount(0);
end;